<?php $empty='<tr><td colspan="8" class="text-center muted py-3">Sin registros para mostrar</td></tr>'; $rol=current_user()['rol']??''; $isAdmin=in_array($rol,['Super Administrador','Administrador'],true); ?>
<form class="dashboard-filters card-dark mb-2" method="get" action="<?= url('dashboard') ?>">
  <div class="row g-2 align-items-end"><div class="col-6 col-md-2"><label>Fecha desde</label><input type="date" name="fecha_desde" value="<?= e($filters['fecha_desde']??'') ?>" class="form-control"></div><div class="col-6 col-md-2"><label>Fecha hasta</label><input type="date" name="fecha_hasta" value="<?= e($filters['fecha_hasta']??'') ?>" class="form-control"></div><div class="col-6 col-md-2"><label>Supervisor</label><select name="supervisor_id" class="form-select"><option value="">Todos</option><?php foreach($catalogos['supervisores'] as $s): ?><option value="<?= $s['id'] ?>" <?= ($filters['supervisor_id']??'')==$s['id']?'selected':'' ?>><?= e($s['nombre']) ?></option><?php endforeach; ?></select></div><div class="col-6 col-md-2"><label>Estado cable</label><select name="estado_cable" class="form-select"><option value="">Todos</option><?php foreach(['disponible','en reparación','entregado','dado de baja'] as $e): ?><option <?= ($filters['estado_cable']??'')===$e?'selected':'' ?>><?= e($e) ?></option><?php endforeach; ?></select></div><div class="col-6 col-md-2"><label>Origen cable</label><select name="origen_cable" class="form-select"><option value="">Todos</option><?php foreach($catalogos['origenes'] as $o): ?><option <?= ($filters['origen_cable']??'')===$o['origen_cable']?'selected':'' ?>><?= e($o['origen_cable']) ?></option><?php endforeach; ?></select></div><div class="col-6 col-md-2 d-flex gap-1"><button class="btn btn-seim btn-sm flex-fill">Filtrar</button><a href="<?= url('dashboard') ?>" class="btn btn-outline-light btn-sm flex-fill">Limpiar</a></div></div>
</form>
<div class="quick-actions card-dark mb-2"><a class="btn btn-seim btn-sm" href="<?= url('informes-cable/crear') ?>">Nuevo informe cable</a><a class="btn btn-outline-light btn-sm" href="<?= url('cables/crear') ?>">Crear cable</a><a class="btn btn-outline-light btn-sm" href="<?= url('entregas-materiales/crear') ?>">Entregar materiales</a><a class="btn btn-outline-light btn-sm" href="<?= url('recepciones-materiales/crear') ?>">Recepcionar materiales</a><a class="btn btn-outline-light btn-sm" href="<?= url('materiales/crear') ?>">Crear material</a><a class="btn btn-outline-light btn-sm" href="<?= url('reportes') ?>">Ver reportes</a></div>
<div class="row g-2 kpi-grid"><?php foreach($stats['kpis'] as $k=>$v): ?><div class="col-6 col-md-3 col-xl-2"><div class="kpi compact"><span><?= e($k) ?></span><strong><?= e((string)$v) ?></strong></div></div><?php endforeach; ?></div>
<div class="row g-2 mt-1">
  <div class="col-lg-3"><div class="card-dark chart-card"><h6>Estado de cables</h6><canvas class="dash-chart" id="chartEstados" data-values='<?= json_encode($stats['cable_estados']) ?>'></canvas></div></div>
  <div class="col-lg-3"><div class="card-dark chart-card"><h6>Informes por estado</h6><canvas class="dash-chart" id="chartInformes" data-values='<?= json_encode($stats['informes_estado']) ?>'></canvas></div></div>
  <div class="col-lg-3"><div class="card-dark chart-card"><h6>Fallas más frecuentes</h6><canvas class="dash-chart" id="chartFallas" data-values='<?= json_encode($stats['fallas']) ?>'></canvas></div></div>
  <div class="col-lg-3"><div class="card-dark chart-card"><h6>Causas probables</h6><canvas class="dash-chart" id="chartCausas" data-values='<?= json_encode($stats['causas']) ?>'></canvas></div></div>
</div>
<div class="row g-2 mt-1"><div class="col-lg-6"><div class="card-dark"><h6>Alertas importantes</h6><div class="alert-board"><?php foreach(['rojas'=>'danger','amarillas'=>'warning','verdes'=>'success'] as $g=>$c): ?><div><b class="text-<?= $c ?>"><?= ucfirst($g) ?></b><?php if(empty($stats['alertas'][$g])): ?><p class="muted mb-1">Sin alertas</p><?php endif; foreach($stats['alertas'][$g] as $a): ?><div class="alert-line border-<?= $c ?>"><span><?= e($a['tipo']) ?></span><small><?= e($a['descripcion']) ?></small></div><?php endforeach; ?></div><?php endforeach; ?></div></div></div>
<div class="col-lg-6"><div class="card-dark"><h6>Materiales más usados</h6><table class="table table-dark table-sm"><thead><tr><th>Foto</th><th>Material</th><th>Categoría</th><th>Usado</th><th>Stock</th><th>Estado</th></tr></thead><tbody><?php if(empty($stats['materiales_usados'])) echo $empty; foreach($stats['materiales_usados'] as $m): $estado=$m['stock_actual']==0?'Crítico':($m['stock_actual']<=$m['stock_minimo']?'Bajo':'Normal'); ?><tr><td><img class="thumb" src="<?= url($m['foto'] ?: 'assets/img/no-photo.svg') ?>"></td><td><?= e($m['nombre_material']) ?></td><td><?= e($m['categoria']??'') ?></td><td><?= e($m['cantidad_utilizada']) ?></td><td><?= e($m['stock_actual'].' / '.$m['stock_minimo']) ?></td><td><?= badge(strtolower($estado)) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php function tbl($title,$headers,$rows,$render,$empty){ ?><div class="col-xl-6"><div class="card-dark"><h6><?= e($title) ?></h6><table class="table table-dark table-sm datatable"><thead><tr><?php foreach($headers as $h): ?><th><?= e($h) ?></th><?php endforeach; ?></tr></thead><tbody><?php if(empty($rows)) echo $empty; foreach($rows as $r) $render($r); ?></tbody></table></div></div><?php } ?>
<div class="row g-2 mt-1">
<?php tbl('Cables con mayor cantidad de reparaciones',['Cable','Marca','Calibre','Informes','Rep.','Última','Estado',''], $stats['cables_reparados'], function($r){ ?><tr><td><?= e($r['numero_cable']) ?></td><td><?= e($r['marca']??'') ?></td><td><?= e($r['calibre']??'') ?></td><td><?= e($r['total_informes']) ?></td><td><?= e($r['total_reparaciones']) ?></td><td><?= e($r['ultima_reparacion']??'') ?></td><td><?= badge($r['estado']) ?></td><td><a class="btn btn-sm btn-outline-light" href="<?= url('cables/historial/'.$r['id']) ?>">Ver historial</a></td></tr><?php },$empty); ?>
<?php tbl('Últimos informes de cable',['Recepción','Entrega','Cable','Supervisor','Origen','Operativo','Informe',''], $stats['ultimos_informes'], function($r){ ?><tr><td><?= e($r['fecha_recepcion_cable']??'') ?></td><td><?= e($r['fecha_entrega_cable']??'') ?></td><td><?= e($r['numero_cable']) ?></td><td><?= e($r['supervisor']??'') ?></td><td><?= e($r['origen_cable']??'') ?></td><td><?= e($r['estado_operativo']??'') ?></td><td><?= badge($r['estado_informe']) ?></td><td><a class="btn btn-sm btn-outline-light" href="<?= url('informes-cable/ver/'.$r['id']) ?>">Ver</a> <a class="btn btn-sm btn-outline-light" href="<?= url('informes-cable/imprimir/'.$r['id']) ?>">Imprimir</a></td></tr><?php },$empty); ?>
<?php tbl('Stock bajo',['Foto','Código','Material','Actual','Mínimo','Unidad','Estado',''], $stats['stock_bajo'], function($m){ $estado=$m['stock_actual']==0?'Crítico':'Bajo'; ?><tr><td><img class="thumb" src="<?= url($m['foto'] ?: 'assets/img/no-photo.svg') ?>"></td><td><?= e($m['codigo_interno']) ?></td><td><?= e($m['nombre_material']) ?></td><td><?= e($m['stock_actual']) ?></td><td><?= e($m['stock_minimo']) ?></td><td><?= e($m['unidad_medida']) ?></td><td><?= badge(strtolower($estado)) ?></td><td><a class="btn btn-sm btn-outline-light" href="<?= url('materiales/editar/'.$m['id']) ?>">Editar</a></td></tr><?php },$empty); ?>
<?php tbl('Entregas de materiales pendientes',['Fecha','Receptor','Materiales','Entregada','Usada','Pendiente','Estado',''], $stats['entregas_pendientes'], function($r){ ?><tr><td><?= e($r['fecha_entrega']) ?></td><td><?= e($r['receptor']) ?></td><td><?= e($r['materiales']) ?></td><td><?= e($r['entregada']) ?></td><td><?= e($r['usada']) ?></td><td><?= e($r['pendiente']) ?></td><td><?= badge($r['estado']) ?></td><td><a class="btn btn-sm btn-outline-light" href="<?= url('entregas-materiales/ver/'.$r['id']) ?>">Ver</a></td></tr><?php },$empty); ?>
<?php tbl('Rendimiento por supervisor',['Supervisor','Creados','Finalizados','Entregados','Rep.','Mat. usados'], $stats['rendimiento'], function($r){ ?><tr><td><?= e($r['supervisor']) ?></td><td><?= e($r['informes_creados']) ?></td><td><?= e($r['informes_finalizados']) ?></td><td><?= e($r['cables_entregados']) ?></td><td><?= e($r['reparaciones']) ?></td><td><?= e($r['materiales_usados']) ?></td></tr><?php },$empty); ?>
<?php if($isAdmin) tbl('Actividad reciente',['Usuario','Acción','Módulo','Descripción','Fecha'], $stats['actividad'], function($r){ ?><tr><td><?= e($r['usuario']??'Sistema') ?></td><td><?= e($r['accion']??'') ?></td><td><?= e($r['modulo']??'') ?></td><td><?= e($r['descripcion']??'') ?></td><td><?= e($r['fecha']??'') ?></td></tr><?php },$empty); ?>
</div>
