<?php
use App\Controllers\{AuthController,DashboardController,CatalogController,MovimientoController,InformeController,ReporteController};
$router->get('', [AuthController::class,'login']); $router->get('login',[AuthController::class,'login']); $router->post('login',[AuthController::class,'authenticate']); $router->get('logout',[AuthController::class,'logout']);
$router->get('dashboard',[DashboardController::class,'index']);
$router->get('dashboard/filtrar',[DashboardController::class,'filtrar']);
$router->get('dashboard/graficos',[DashboardController::class,'obtenerDatosGraficosAjax']);
$router->get('dashboard/alertas',[DashboardController::class,'alertas']);
$router->get('dashboard/kpis',[DashboardController::class,'kpis']);
$router->get('usuarios',[CatalogController::class,'usuarios']); $router->get('usuarios/crear',[CatalogController::class,'usuarios']); $router->get('usuarios/editar/{id}',[CatalogController::class,'usuarios']); $router->get('usuarios/ver/{id}',[CatalogController::class,'usuarios']);
$router->get('roles',[CatalogController::class,'roles']); $router->get('roles/crear',[CatalogController::class,'roles']); $router->get('roles/editar/{id}',[CatalogController::class,'roles']);
$router->get('materiales',[CatalogController::class,'materiales']); $router->get('materiales/crear',[CatalogController::class,'materialForm']); $router->get('materiales/editar/{id}',[CatalogController::class,'materialForm']); $router->get('materiales/ver/{id}',[CatalogController::class,'materialForm']); $router->post('materiales/guardar',[CatalogController::class,'saveMaterial']);
$router->get('entregas-materiales',[MovimientoController::class,'entregas']); $router->get('entregas-materiales/crear',[MovimientoController::class,'formEntrega']); $router->post('entregas-materiales/guardar',[MovimientoController::class,'saveEntrega']); $router->get('entregas-materiales/ver/{id}',[MovimientoController::class,'entregas']);
$router->get('recepciones-materiales',[MovimientoController::class,'recepciones']); $router->get('recepciones-materiales/crear',[MovimientoController::class,'recepciones']); $router->get('recepciones-materiales/ver/{id}',[MovimientoController::class,'recepciones']);
$router->get('cables',[CatalogController::class,'cables']); $router->get('cables/crear',[CatalogController::class,'cableForm']); $router->get('cables/editar/{id}',[CatalogController::class,'cableForm']); $router->get('cables/ver/{id}',[CatalogController::class,'cableForm']); $router->post('cables/guardar',[CatalogController::class,'saveCable']); $router->get('cables/historial/{id}',[CatalogController::class,'historial']);
$router->get('informes-cable',[InformeController::class,'index']); $router->get('informes-cable/crear',[InformeController::class,'form']); $router->get('informes-cable/editar/{id}',[InformeController::class,'form']); $router->get('informes-cable/ver/{id}',[InformeController::class,'form']); $router->post('informes-cable/guardar',[InformeController::class,'save']); $router->get('informes-cable/imprimir/{id}',[InformeController::class,'print']);
$router->get('marcas-cable',[CatalogController::class,'marcas']); $router->get('reportes',[ReporteController::class,'index']);
