<?php
$usuariosMateriales = $materialesUsuario ?? [];
$usuariosConMateriales = [];
foreach ($usuariosMateriales as $mu) $usuariosConMateriales[$mu['usuario_receptor_id']] = $mu['usuario'];
$selectedValues = [];
foreach (['fallas_chaquetas','fallas_enchufe','lugares_falla','causas_probables','pruebas_continuidad','prueba_ez_thump','continuidad_final','vlf','pruebas_finales'] as $field) {
    $raw = $item[$field] ?? '[]';
    $decoded = is_string($raw) ? json_decode($raw, true) : [];
    $selectedValues[$field] = is_array($decoded) ? $decoded : [];
}
function checked_nested(array $values, string $group, string $item, string $key): string { return !empty($values[$group][$item][$key]) ? 'checked' : ''; }
function value_nested(array $values, string $group, string $item, string $key): string { return e($values[$group][$item][$key] ?? ''); }
$isEdit = !empty($item['id']);
?>
<div class="report-shell">
  <div class="report-hero">
    <div>
      <span class="report-eyebrow">Informe técnico</span>
      <h1><?= $isEdit ? 'Editar informe diario de reparación' : 'Nuevo informe diario de reparación' ?></h1>
      <p>Complete la recepción, diagnóstico, pruebas, materiales utilizados y entrega final. Todos los datos del formulario se guardan en la base de datos del informe.</p>
    </div>
    <div class="report-hero-actions">
      <a class="btn btn-outline-light" href="<?= url('informes-cable') ?>">Volver al listado</a>
      <button class="btn btn-seim" form="informeCableForm">Guardar informe</button>
    </div>
  </div>

  <form id="informeCableForm" method="post" action="<?= url($isEdit ? 'informes-cable/guardar/'.$item['id'] : 'informes-cable/guardar') ?>" class="report-form report-form-pro">
    <?= csrf_field() ?>
    <input type="hidden" name="id" value="<?= e($item['id']??'') ?>">

    <section class="report-section report-section-wide">
      <div class="section-head"><span>1</span><div><h2>Cabecera del informe</h2><p>Identificación general, fechas y cable a intervenir.</p></div></div>
      <div class="row g-3">
        <div class="col-lg-3 col-md-6"><label>Supervisor responsable</label><select name="supervisor_id" class="form-select" required><option value="">Seleccione...</option><?php foreach($supervisores as $s): ?><option value="<?= $s['id'] ?>" <?= ($item['supervisor_id']??'')==$s['id']?'selected':'' ?>><?= e($s['nombre'].' '.$s['apellido']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-2 col-md-6"><label>Fecha recepción</label><input type="date" class="form-control" name="fecha_recepcion_cable" value="<?= e($item['fecha_recepcion_cable']??date('Y-m-d')) ?>" required></div>
        <div class="col-lg-2 col-md-6"><label>Fecha entrega</label><input type="date" class="form-control" name="fecha_entrega_cable" value="<?= e($item['fecha_entrega_cable']??'') ?>"></div>
        <div class="col-lg-3 col-md-6"><label>Cable</label><select id="cableSelect" name="cable_id" class="form-select" required><option value="">Seleccione cable...</option><?php foreach($cables as $c): ?><option data-json='<?= e(json_encode($c)) ?>' value="<?= $c['id'] ?>" <?= ($item['cable_id']??'')==$c['id']?'selected':'' ?>><?= e($c['numero_cable']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-2 col-md-6"><label>Estado informe</label><select name="estado_informe" class="form-select"><?php foreach(['borrador','finalizado','anulado'] as $e): ?><option value="<?= e($e) ?>" <?= ($item['estado_informe']??'borrador')===$e?'selected':'' ?>><?= ucfirst($e) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-4 col-md-6"><label>Origen cable</label><select name="origen_cable" class="form-select"><option value="">Seleccione origen...</option><?php foreach($origenes as $o): ?><option value="<?= e($o['nombre']) ?>" <?= ($item['origen_cable']??'')===$o['nombre']?'selected':'' ?>><?= e($o['nombre']) ?></option><?php endforeach; ?></select></div>
      </div>
    </section>

    <section class="report-section"><div class="section-head"><span>2</span><div><h2>Datos de recepción</h2><p>Información cargada automáticamente desde el cable seleccionado.</p></div></div><div id="cableInfo" class="info-grid report-info-grid"></div></section>
    <section class="report-section"><div class="section-head"><span>3</span><div><h2>Reparaciones</h2><p>Cantidades al ingresar y al salir.</p></div></div><div class="repair-grid"><?php foreach(['rep_ing_mufas_termo'=>'Ingreso · Mufas termocontraíbles','rep_ing_mufa_union'=>'Ingreso · Mufa de unión','rep_ing_chaquetas'=>'Ingreso · Chaquetas','rep_sal_mufas_termo'=>'Salida · Mufas termocontraíbles','rep_sal_mufa_union'=>'Salida · Mufa de unión','rep_sal_chaquetas'=>'Salida · Chaquetas'] as $n=>$l): ?><div><label><?= $l ?></label><input type="number" min="0" name="<?= $n ?>" class="form-control" value="<?= e($item[$n]??0) ?>"></div><?php endforeach; ?></div></section>

    <section class="report-section report-section-wide"><div class="section-head"><span>4</span><div><h2>Entrega del cable</h2><p>Condición operativa y atributos con los que se entrega el cable.</p></div></div><div class="row g-3"><div class="col-lg-2 col-md-4"><label>Estado operativo</label><select name="estado_operativo" class="form-select"><option value="">Seleccione...</option><?php foreach(['Operativo','No operativo','En observación','Dado de baja'] as $e): ?><option value="<?= e($e) ?>" <?= ($item['estado_operativo']??'')===$e?'selected':'' ?>><?= e($e) ?></option><?php endforeach; ?></select></div><div class="col-lg-2 col-md-4"><label>Destino</label><input name="destino_cable" class="form-control" value="<?= e($item['destino_cable']??'') ?>"></div><div class="col-lg-2 col-md-4"><label>Tipo enchufe</label><input name="tipo_enchufe_entrega" class="form-control" value="<?= e($item['tipo_enchufe_entrega']??'') ?>"></div><div class="col-lg-2 col-md-4"><label>Largo entrega</label><input name="largo_entrega" class="form-control" value="<?= e($item['largo_entrega']??'') ?>"></div><div class="col-lg-2 col-md-4"><label>Marca</label><input name="marca_entrega" class="form-control" value="<?= e($item['marca_entrega']??'') ?>"></div><div class="col-lg-2 col-md-4"><label>Capacidad aislación</label><input name="capacidad_aislacion_entrega" class="form-control" value="<?= e($item['capacidad_aislacion_entrega']??'') ?>"></div></div></section>

    <section class="report-section"><div class="section-head"><span>5</span><div><h2>Falla chaquetas/mufas</h2><p>Seleccione todas las condiciones detectadas.</p></div></div><div class="choice-grid"><?php foreach($inf->fallasChaquetas as $o): ?><label class="choice-chip"><input type="checkbox" name="fallas_chaquetas[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['fallas_chaquetas'], true) ? 'checked' : '' ?>><span><?= e($o) ?></span></label><?php endforeach; ?></div></section>
    <section class="report-section"><div class="section-head"><span>6</span><div><h2>Falla enchufe</h2><p>Registre daños o ausencias del enchufe.</p></div></div><div class="choice-grid"><?php foreach($inf->fallasEnchufe as $o): ?><label class="choice-chip"><input type="checkbox" name="fallas_enchufe[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['fallas_enchufe'], true) ? 'checked' : '' ?>><span><?= e($o) ?></span></label><?php endforeach; ?></div></section>

    <?php foreach(['pruebas_continuidad'=>['7','Prueba de continuidad',['Fase N° 1','Fase N° 2','Fase N° 3','Piloto']],'prueba_ez_thump'=>['8','Prueba EZ-THUMP 12',['Fase N° 1','Fase N° 2','Fase N° 3','Piloto']],'continuidad_final'=>['9','Continuidad final',['Hilo piloto','Fase N° 1','Fase N° 2','Fase N° 3','Tierra']],'vlf'=>['10','VLF',['Fase N° 1','Fase N° 2','Fase N° 3']]] as $field=>[$num,$title,$items]): ?><section class="report-section"><div class="section-head"><span><?= $num ?></span><div><h2><?= $title ?></h2><p>Active la prueba realizada y marque si presentó falla.</p></div></div><?php foreach($items as $it): ?><div class="switch-line"><span><?= e($it) ?></span><input type="hidden" name="<?= e($field) ?>[<?= e($it) ?>][realizada]" value="0"><label class="switch"><input type="checkbox" name="<?= e($field) ?>[<?= e($it) ?>][realizada]" value="1" class="revision-card-realizada" <?= checked_nested($selectedValues, $field, $it, 'realizada') ?>><b></b></label><label class="fault-check"><input type="checkbox" name="<?= e($field) ?>[<?= e($it) ?>][con_falla]" value="1" class="revision-card-falla" <?= checked_nested($selectedValues, $field, $it, 'con_falla') ?>> Con falla</label></div><?php endforeach; ?></section><?php endforeach; ?>

    <section class="report-section"><div class="section-head"><span>11</span><div><h2>Lugar de la falla</h2><p>Ubicación técnica del defecto.</p></div></div><div class="choice-grid"><?php foreach($inf->lugares as $o): ?><label class="choice-chip"><input type="checkbox" name="lugares_falla[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['lugares_falla'], true) ? 'checked' : '' ?>><span><?= e($o) ?></span></label><?php endforeach; ?></div></section>
    <section class="report-section"><div class="section-head"><span>12</span><div><h2>Causa probable</h2><p>Seleccione una o más causas identificadas.</p></div></div><div class="choice-grid"><?php foreach($inf->causas as $o): ?><label class="choice-chip"><input type="checkbox" name="causas_probables[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['causas_probables'], true) ? 'checked' : '' ?>><span><?= e($o) ?></span></label><?php endforeach; ?></div></section>

    <section class="report-section report-section-wide"><div class="section-head"><span>13</span><div><h2>Pruebas finales cable</h2><p>Ingrese el valor por fase y unidad de medición.</p></div></div><div class="row g-3"><?php foreach(['1min','3min'] as $min): foreach(['Fase N° 1','Fase N° 2','Fase N° 3','Hilo piloto'] as $it): $key=$it.' / '.$min; ?><div class="col-lg-3 col-md-6"><label><?= e($key) ?></label><div class="input-group input-group-sm"><input type="hidden" name="pruebas_finales[<?= e($key) ?>][realizada]" value="0"><span class="input-group-text"><input type="checkbox" name="pruebas_finales[<?= e($key) ?>][realizada]" value="1" class="revision-card-realizada" <?= checked_nested($selectedValues, 'pruebas_finales', $key, 'realizada') ?>></span><input class="form-control" name="pruebas_finales[<?= e($key) ?>][valor]" placeholder="Valor" value="<?= value_nested($selectedValues, 'pruebas_finales', $key, 'valor') ?>"><select class="form-select" name="pruebas_finales[<?= e($key) ?>][unidad]"><option value="Mega Ohm" <?= (($selectedValues['pruebas_finales'][$key]['unidad']??'')==='Mega Ohm')?'selected':'' ?>>Mega Ohm</option><option value="Giga Ohm" <?= (($selectedValues['pruebas_finales'][$key]['unidad']??'')==='Giga Ohm')?'selected':'' ?>>Giga Ohm</option></select></div></div><?php endforeach; endforeach; ?></div></section>

    <section class="report-section report-section-wide"><div class="section-head"><span>14</span><div><h2>Materiales usados</h2><p>Seleccione usuario, material entregado y cantidad utilizada. El stock disponible se descuenta al guardar.</p></div></div><div id="informeMaterialRows"><?php if(empty($usuariosMateriales)): ?><div class="alert alert-warning py-2">No hay materiales entregados disponibles para uso.</div><?php else: ?><?php $rowsMateriales = !empty($materialesInforme) ? $materialesInforme : [null]; foreach($rowsMateriales as $materialActual): ?><div class="row g-3 mb-2 informe-material-row"><div class="col-md-4"><label>Usuario</label><select class="form-select informe-material-user"><option value="">Seleccione usuario...</option><?php foreach($usuariosConMateriales as $uid=>$nombre): ?><option value="<?= e($uid) ?>" <?= $materialActual && (int)$materialActual['usuario_receptor_id']===(int)$uid?'selected':'' ?>><?= e($nombre) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><label>Material entregado</label><select name="material_detalle_id[]" class="form-select informe-material-select"><option value="">Seleccione material...</option><?php foreach($usuariosMateriales as $mu): ?><option value="<?= e($mu['detalle_id']) ?>" data-user="<?= e($mu['usuario_receptor_id']) ?>" data-disponible="<?= e($mu['cantidad_disponible']) ?>" <?= $materialActual && (int)$materialActual['detalle_id']===(int)$mu['detalle_id']?'selected':'' ?>><?= e($mu['codigo_interno'].' · '.$mu['nombre_material'].' (disp. '.$mu['cantidad_disponible'].' '.$mu['unidad_medida'].')') ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label>Cantidad usada</label><input type="number" step="0.01" min="0" name="material_cantidad[]" class="form-control informe-material-cantidad" placeholder="0" value="<?= e($materialActual['cantidad_utilizada']??'') ?>"></div><div class="col-md-1 d-flex align-items-end"><button type="button" class="btn btn-outline-light w-100 remove-informe-material">×</button></div></div><?php endforeach; ?><?php endif; ?></div><?php if(!empty($usuariosMateriales)): ?><button type="button" class="btn btn-sm btn-outline-light mt-2" id="addInformeMaterial">Agregar material usado</button><?php endif; ?></section>

    <section class="report-section report-section-wide"><div class="section-head"><span>15</span><div><h2>Observación final</h2><p>Notas de cierre, recomendaciones o restricciones operativas.</p></div></div><textarea class="form-control" name="observacion_final" rows="4" placeholder="Escriba observaciones relevantes para trazabilidad del informe..."><?= e($item['observacion_final']??'') ?></textarea></section>
    <div class="report-submit"><a class="btn btn-outline-light" href="<?= url('informes-cable') ?>">Cancelar</a><button class="btn btn-seim">Guardar informe</button></div>
  </form>
</div>
