<?php
$usuariosMateriales = $materialesUsuario ?? [];
$usuariosConMateriales = [];
foreach ($usuariosMateriales as $mu) $usuariosConMateriales[$mu['usuario_receptor_id']] = $mu['usuario'];
$selectedValues = [];
foreach (['fallas_chaquetas','fallas_enchufe','lugares_falla','causas_probables'] as $field) {
    $raw = $item[$field] ?? '[]';
    $decoded = is_string($raw) ? json_decode($raw, true) : [];
    $selectedValues[$field] = is_array($decoded) ? $decoded : [];
}
?>
<div class="card-dark"><h5>Informe diario de reparación cables mineros</h5><form method="post" action="<?= url(!empty($item['id']) ? 'informes-cable/guardar/'.$item['id'] : 'informes-cable/guardar') ?>" class="row g-2 report-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($item['id']??'') ?>">
<section class="col-12 panel"><h6>Cabecera</h6><div class="row g-2"><div class="col-md-3"><label>Supervisor</label><select name="supervisor_id" class="form-select"><?php foreach($supervisores as $s): ?><option value="<?= $s['id'] ?>" <?= ($item['supervisor_id']??'')==$s['id']?'selected':'' ?>><?= e($s['nombre'].' '.$s['apellido']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label>Fecha recepción</label><input type="date" class="form-control" name="fecha_recepcion_cable" value="<?= e($item['fecha_recepcion_cable']??date('Y-m-d')) ?>"></div><div class="col-md-2"><label>Fecha entrega</label><input type="date" class="form-control" name="fecha_entrega_cable" value="<?= e($item['fecha_entrega_cable']??'') ?>"></div><div class="col-md-3"><label>Cable</label><select id="cableSelect" name="cable_id" class="form-select"><?php foreach($cables as $c): ?><option data-json='<?= e(json_encode($c)) ?>' value="<?= $c['id'] ?>" <?= ($item['cable_id']??'')==$c['id']?'selected':'' ?>><?= e($c['numero_cable']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label>Estado informe</label><select name="estado_informe" class="form-select"><?php foreach(['borrador','finalizado','anulado'] as $e): ?><option <?= ($item['estado_informe']??'')===$e?'selected':'' ?>><?= $e ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label>Origen cable</label><select name="origen_cable" class="form-select"><option value="">Seleccione origen...</option><?php foreach($origenes as $o): ?><option value="<?= e($o['nombre']) ?>" <?= ($item['origen_cable']??'')===$o['nombre']?'selected':'' ?>><?= e($o['nombre']) ?></option><?php endforeach; ?></select></div></div></section>
<section class="col-md-6 panel"><h6>Recepción cable</h6><div id="cableInfo" class="info-grid"></div></section>
<section class="col-md-3 panel"><h6>Reparaciones al ingresar</h6><?php foreach(['rep_ing_mufas_termo'=>'Mufas Termocontraible','rep_ing_mufa_union'=>'Mufa de unión','rep_ing_chaquetas'=>'Chaquetas'] as $n=>$l): ?><label><?= $l ?></label><input type="number" name="<?= $n ?>" class="form-control" value="<?= e($item[$n]??0) ?>"><?php endforeach; ?></section>
<section class="col-md-3 panel"><h6>Reparaciones al salir</h6><?php foreach(['rep_sal_mufas_termo'=>'Mufas Termocontraible','rep_sal_mufa_union'=>'Mufa de unión','rep_sal_chaquetas'=>'Chaquetas'] as $n=>$l): ?><label><?= $l ?></label><input type="number" name="<?= $n ?>" class="form-control" value="<?= e($item[$n]??0) ?>"><?php endforeach; ?></section>
<section class="col-12 panel"><h6>Estado entrega cable</h6><div class="row g-2"><div class="col-md-2"><select name="estado_operativo" class="form-select"><?php foreach(['Operativo','No operativo','En observación','Dado de baja'] as $e): ?><option <?= ($item['estado_operativo']??'')===$e?'selected':'' ?>><?= $e ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input name="destino_cable" class="form-control" placeholder="Destino" value="<?= e($item['destino_cable']??'') ?>"></div><div class="col-md-2"><input name="tipo_enchufe_entrega" class="form-control" placeholder="Tipo enchufe" value="<?= e($item['tipo_enchufe_entrega']??'') ?>"></div><div class="col-md-2"><input name="largo_entrega" class="form-control" placeholder="Largo entrega" value="<?= e($item['largo_entrega']??'') ?>"></div><div class="col-md-2"><input name="marca_entrega" class="form-control" placeholder="Marca" value="<?= e($item['marca_entrega']??'') ?>"></div><div class="col-md-2"><input name="capacidad_aislacion_entrega" class="form-control" placeholder="Capacidad aislación" value="<?= e($item['capacidad_aislacion_entrega']??'') ?>"></div></div></section>
<section class="col-md-6 panel"><h6>Falla Chaquetas/Mufas</h6><?php foreach($inf->fallasChaquetas as $o): ?><label class="check"><input type="checkbox" name="fallas_chaquetas[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['fallas_chaquetas'], true) ? 'checked' : '' ?>> <?= e($o) ?></label><?php endforeach; ?></section>
<section class="col-md-6 panel"><h6>Falla Enchufe</h6><?php foreach($inf->fallasEnchufe as $o): ?><label class="check"><input type="checkbox" name="fallas_enchufe[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['fallas_enchufe'], true) ? 'checked' : '' ?>> <?= e($o) ?></label><?php endforeach; ?></section>
<?php foreach(['Prueba de continuidad'=>['Fase N° 1','Fase N° 2','Fase N° 3','Piloto'],'Prueba EZ-THUMP 12'=>['Fase N° 1','Fase N° 2','Fase N° 3','Piloto'],'Continuidad final'=>['Hilo piloto','Fase N° 1','Fase N° 2','Fase N° 3','Tierra'],'VLF'=>['Fase N° 1','Fase N° 2','Fase N° 3']] as $title=>$items): ?><section class="col-md-6 panel"><h6><?= $title ?></h6><?php foreach($items as $it): ?><div class="switch-line"><span><?= e($it) ?></span><label class="switch"><input type="checkbox"><b></b></label><label class="fault-check"><input type="checkbox"> Con falla</label></div><?php endforeach; ?></section><?php endforeach; ?>
<section class="col-md-6 panel"><h6>Lugar de la falla</h6><?php foreach($inf->lugares as $o): ?><label class="check"><input type="checkbox" name="lugares_falla[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['lugares_falla'], true) ? 'checked' : '' ?>> <?= e($o) ?></label><?php endforeach; ?></section>
<section class="col-md-6 panel"><h6>Causa probable</h6><?php foreach($inf->causas as $o): ?><label class="check"><input type="checkbox" name="causas_probables[]" value="<?= e($o) ?>" <?= in_array($o, $selectedValues['causas_probables'], true) ? 'checked' : '' ?>> <?= e($o) ?></label><?php endforeach; ?></section>
<section class="col-12 panel"><h6>Pruebas finales cable</h6><div class="row g-2"><?php foreach(['1min','3min'] as $min): foreach(['Fase N° 1','Fase N° 2','Fase N° 3','Hilo piloto'] as $it): ?><div class="col-md-3"><label><?= e($it.' / '.$min) ?></label><div class="input-group input-group-sm"><span class="input-group-text"><input type="checkbox"></span><input class="form-control" placeholder="Valor"><select class="form-select"><option>Mega Ohm</option><option>Giga Ohm</option></select></div></div><?php endforeach; endforeach; ?></div></section>
<section class="col-12 panel"><h6>Materiales usados</h6><p class="muted">Seleccione uno o más usuarios y luego los materiales pendientes asociados a sus entregas activas.</p><div id="informeMaterialRows"><?php if(empty($usuariosMateriales)): ?><div class="alert alert-warning py-2">No hay materiales entregados disponibles para uso.</div><?php else: ?><div class="row g-2 mb-2 informe-material-row"><div class="col-md-4"><label>Usuario</label><select class="form-select informe-material-user"><option value="">Seleccione usuario...</option><?php foreach($usuariosConMateriales as $uid=>$nombre): ?><option value="<?= e($uid) ?>"><?= e($nombre) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><label>Material entregado</label><select name="material_detalle_id[]" class="form-select informe-material-select"><option value="">Seleccione material...</option><?php foreach($usuariosMateriales as $mu): ?><option value="<?= e($mu['detalle_id']) ?>" data-user="<?= e($mu['usuario_receptor_id']) ?>" data-disponible="<?= e($mu['cantidad_disponible']) ?>"><?= e($mu['codigo_interno'].' · '.$mu['nombre_material'].' (disp. '.$mu['cantidad_disponible'].' '.$mu['unidad_medida'].')') ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label>Cantidad usada</label><input type="number" step="0.01" min="0" name="material_cantidad[]" class="form-control informe-material-cantidad" placeholder="0"></div><div class="col-md-1 d-flex align-items-end"><button type="button" class="btn btn-outline-light w-100 remove-informe-material">×</button></div></div><?php endif; ?></div><?php if(!empty($usuariosMateriales)): ?><button type="button" class="btn btn-sm btn-outline-light" id="addInformeMaterial">Agregar material usado</button><?php endif; ?></section>
<section class="col-12 panel"><h6>Observación final</h6><textarea class="form-control" name="observacion_final"><?= e($item['observacion_final']??'') ?></textarea></section><div class="col-12"><button class="btn btn-seim">Guardar informe</button></div></form></div>
