<?php
namespace App\Controllers;
use App\Core\Controller; use App\Models\BaseCatalog; use App\Models\InventoryModel;
class CatalogController extends Controller {
 public function usuarios():void{$this->requirePermission('Usuarios');$m=new BaseCatalog;$rows=$m->fetchAll('SELECT u.*, r.nombre rol FROM usuarios u JOIN roles r ON r.id=u.rol_id WHERE u.deleted_at IS NULL ORDER BY u.id DESC');$this->view('usuarios/index',compact('rows'));}
 public function roles():void{$this->requirePermission('Roles');$m=new BaseCatalog;$rows=$m->all('roles');$this->view('roles/index',compact('rows'));}
 public function marcas():void{$this->requirePermission('Marcas de cable');$m=new BaseCatalog;$rows=$m->all('marcas_cable');$this->view('marcas/index',compact('rows'));}
 public function materiales():void{$this->requirePermission('Materiales');$m=new InventoryModel;$rows=$m->materiales();$cats=$m->all('categorias_materiales','nombre');$this->view('materiales/index',compact('rows','cats'));}
 public function materialForm($id=null):void{$this->requirePermission('Materiales',$id?'editar':'crear');$m=new InventoryModel;$item=$id?$m->find('materiales',(int)$id):null;$cats=$m->all('categorias_materiales','nombre');$this->view('materiales/form',compact('item','cats'));}
 public function saveMaterial():void{verify_csrf();$this->requirePermission('Materiales',($_POST['id']??'')?'editar':'crear');$m=new InventoryModel;$foto=$this->uploadImage('foto','materiales');$id=$m->guardarMaterial($_POST+['foto'=>$foto],($_POST['id']??'')?(int)$_POST['id']:null);$m->audit('Guardar','Materiales',$id,'Material guardado');flash('success','Material guardado.');redirect('materiales');}
 public function cables():void{$this->requirePermission('Cables');$m=new BaseCatalog;$rows=$m->fetchAll('SELECT c.*, mc.nombre marca FROM cables c LEFT JOIN marcas_cable mc ON mc.id=c.marca_id WHERE c.deleted_at IS NULL ORDER BY c.id DESC');$this->view('cables/index',compact('rows'));}
 public function cableForm($id=null):void{$this->requirePermission('Cables',$id?'editar':'crear');$m=new BaseCatalog;$item=$id?$m->find('cables',(int)$id):null;$marcas=$m->all('marcas_cable','nombre');$this->view('cables/form',compact('item','marcas'));}
 public function saveCable():void{verify_csrf();$this->requirePermission('Cables',($_POST['id']??'')?'editar':'crear');$m=new BaseCatalog;$img=$this->uploadImage('imagen','cables');$p=[$_POST['numero_cable'],$_POST['marca_id'],$_POST['calibre'],$_POST['tipo_enchufe'],$_POST['aislacion'],$_POST['largo'],$_POST['capacidad_aislacion'],$img,$_POST['estado'],$_POST['observacion']]; if(!empty($_POST['id'])){$p[]=$_POST['id'];$m->execSql('UPDATE cables SET numero_cable=?,marca_id=?,calibre=?,tipo_enchufe=?,aislacion=?,largo=?,capacidad_aislacion=?,imagen=COALESCE(?,imagen),estado=?,observacion=?,updated_at=NOW() WHERE id=?',$p);$id=(int)$_POST['id'];}else{$m->execSql('INSERT INTO cables(numero_cable,marca_id,calibre,tipo_enchufe,aislacion,largo,capacidad_aislacion,imagen,estado,observacion,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$p);$id=(int)\App\Core\App::db()->lastInsertId();}$m->audit('Guardar','Cables',$id,'Cable guardado');flash('success','Cable guardado.');redirect('cables');}
 public function historial($id):void{$this->requirePermission('Cables');$m=new BaseCatalog;$cable=$m->fetch('SELECT c.*, mc.nombre marca FROM cables c LEFT JOIN marcas_cable mc ON mc.id=c.marca_id WHERE c.id=?',[$id]);$informes=$m->fetchAll('SELECT * FROM informes_cable WHERE cable_id=? ORDER BY id DESC',[$id]);$this->view('cables/historial',compact('cable','informes'));}
}
