<?php
namespace App\Controllers;
use App\Core\Controller; use App\Models\BaseCatalog; use App\Models\InventoryModel;
class CatalogController extends Controller {
 public function usuarios():void{$this->requirePermission('Usuarios');$m=new BaseCatalog;$rows=$m->fetchAll('SELECT u.*, r.nombre rol FROM usuarios u JOIN roles r ON r.id=u.rol_id WHERE u.deleted_at IS NULL ORDER BY u.id DESC');$this->view('usuarios/index',compact('rows'));}
 public function usuarioForm($id=null):void{$this->requirePermission('Usuarios',$id?'editar':'crear');$m=new BaseCatalog;$item=$id?$m->find('usuarios',(int)$id):null;$roles=$m->all('roles','nombre');$this->view('usuarios/form',compact('item','roles'));}
 public function saveUsuario():void{verify_csrf();$this->requirePermission('Usuarios',($_POST['id']??'')?'editar':'crear');$m=new BaseCatalog;$id=($_POST['id']??'')?(int)$_POST['id']:null;$pass=trim($_POST['password']??'');if(!$id&&$pass===''){flash('error','La contraseña es obligatoria para usuarios nuevos.');redirect('usuarios/crear');}try{if($id){$p=[$_POST['nombre'],$_POST['apellido'],$_POST['usuario'],$_POST['email'],$_POST['telefono'],$_POST['cargo'],$_POST['area'],$_POST['rol_id'],$_POST['estado']];$sql='UPDATE usuarios SET nombre=?,apellido=?,usuario=?,email=?,telefono=?,cargo=?,area=?,rol_id=?,estado=?,updated_at=NOW()';if($pass!==''){$sql.=',password=?';$p[]=password_hash($pass,PASSWORD_DEFAULT);}$sql.=' WHERE id=?';$p[]=$id;$m->execSql($sql,$p);}else{$m->execSql('INSERT INTO usuarios(nombre,apellido,usuario,email,telefono,cargo,area,rol_id,estado,password,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$_POST['nombre'],$_POST['apellido'],$_POST['usuario'],$_POST['email'],$_POST['telefono'],$_POST['cargo'],$_POST['area'],$_POST['rol_id'],$_POST['estado'],password_hash($pass,PASSWORD_DEFAULT)]);$id=(int)\App\Core\App::db()->lastInsertId();}$m->audit('Guardar','Usuarios',$id,'Usuario guardado');flash('success','Usuario guardado.');redirect('usuarios');}catch(\Throwable $e){flash('error','No se pudo guardar el usuario: '.$e->getMessage());redirect($id?'usuarios/editar/'.$id:'usuarios/crear');}}
 public function roles():void{$this->requirePermission('Roles');$m=new BaseCatalog;$rows=$m->all('roles');$this->view('roles/index',compact('rows'));}
 public function rolForm($id=null):void{$this->requirePermission('Roles',$id?'editar':'crear');$m=new BaseCatalog;$item=$id?$m->find('roles',(int)$id):null;$permisos=$m->fetchAll('SELECT modulo,permiso FROM permisos ORDER BY modulo,permiso');$activos=[];if($id){foreach($m->fetchAll('SELECT modulo,permiso FROM rol_permiso WHERE rol_id=? AND permitido=1',[$id]) as $p)$activos[$p['modulo']][$p['permiso']]=true;}$this->view('roles/form',compact('item','permisos','activos'));}
 public function saveRol():void{verify_csrf();$this->requirePermission('Roles',($_POST['id']??'')?'editar':'crear');$m=new BaseCatalog;$db=\App\Core\App::db();$id=($_POST['id']??'')?(int)$_POST['id']:null;$db->beginTransaction();try{if($id){$m->execSql('UPDATE roles SET nombre=?,estado=?,updated_at=NOW() WHERE id=?',[$_POST['nombre'],$_POST['estado'],$id]);$m->execSql('DELETE FROM rol_permiso WHERE rol_id=?',[$id]);}else{$m->execSql('INSERT INTO roles(nombre,estado,created_at,updated_at) VALUES(?,?,NOW(),NOW())',[$_POST['nombre'],$_POST['estado']]);$id=(int)$db->lastInsertId();}$sel=$_POST['permisos']??[];foreach($m->fetchAll('SELECT modulo,permiso FROM permisos ORDER BY modulo,permiso') as $p){$permitido=!empty($sel[$p['modulo']][$p['permiso']])?1:0;$m->execSql('INSERT INTO rol_permiso(rol_id,modulo,permiso,permitido) VALUES(?,?,?,?)',[$id,$p['modulo'],$p['permiso'],$permitido]);}$m->audit('Guardar','Roles',$id,'Rol guardado');$db->commit();flash('success','Rol guardado.');redirect('roles');}catch(\Throwable $e){$db->rollBack();flash('error','No se pudo guardar el rol: '.$e->getMessage());redirect($id?'roles/editar/'.$id:'roles/crear');}}
 public function marcas():void{$this->requirePermission('Marcas de cable');$m=new BaseCatalog;$rows=$m->all('marcas_cable');$this->view('marcas/index',compact('rows'));}
 public function marcaForm($id=null):void{$this->requirePermission('Marcas de cable',$id?'editar':'crear');$m=new BaseCatalog;$item=$id?$m->find('marcas_cable',(int)$id):null;$this->view('marcas/form',compact('item'));}
 public function saveMarca():void{verify_csrf();$this->requirePermission('Marcas de cable',($_POST['id']??'')?'editar':'crear');$m=new BaseCatalog;$id=($_POST['id']??'')?(int)$_POST['id']:null;try{if($id){$m->execSql('UPDATE marcas_cable SET nombre=?,estado=?,updated_at=NOW() WHERE id=?',[$_POST['nombre'],$_POST['estado'],$id]);}else{$m->execSql('INSERT INTO marcas_cable(nombre,estado,created_at,updated_at) VALUES(?,?,NOW(),NOW())',[$_POST['nombre'],$_POST['estado']]);$id=(int)\App\Core\App::db()->lastInsertId();}$m->audit('Guardar','Marcas de cable',$id,'Marca guardada');flash('success','Marca guardada.');redirect('marcas-cable');}catch(\Throwable $e){flash('error','No se pudo guardar la marca: '.$e->getMessage());redirect($id?'marcas-cable/editar/'.$id:'marcas-cable/crear');}}
 public function materiales():void{$this->requirePermission('Materiales');$m=new InventoryModel;$rows=$m->materiales();$cats=$m->all('categorias_materiales','nombre');$this->view('materiales/index',compact('rows','cats'));}
 public function materialForm($id=null):void{$this->requirePermission('Materiales',$id?'editar':'crear');$m=new InventoryModel;$item=$id?$m->find('materiales',(int)$id):null;$cats=$m->all('categorias_materiales','nombre');$this->view('materiales/form',compact('item','cats'));}
 public function saveMaterial():void{verify_csrf();$this->requirePermission('Materiales',($_POST['id']??'')?'editar':'crear');$m=new InventoryModel;$foto=$this->uploadImage('foto','materiales');$id=$m->guardarMaterial($_POST+['foto'=>$foto],($_POST['id']??'')?(int)$_POST['id']:null);$m->audit('Guardar','Materiales',$id,'Material guardado');flash('success','Material guardado.');redirect('materiales');}
 public function cables():void{$this->requirePermission('Cables');$m=new BaseCatalog;$rows=$m->fetchAll('SELECT c.*, mc.nombre marca FROM cables c LEFT JOIN marcas_cable mc ON mc.id=c.marca_id WHERE c.deleted_at IS NULL ORDER BY c.id DESC');$this->view('cables/index',compact('rows'));}
 public function cableForm($id=null):void{$this->requirePermission('Cables',$id?'editar':'crear');$m=new BaseCatalog;$item=$id?$m->find('cables',(int)$id):null;$marcas=$m->all('marcas_cable','nombre');$this->view('cables/form',compact('item','marcas'));}
 public function saveCable():void{verify_csrf();$this->requirePermission('Cables',($_POST['id']??'')?'editar':'crear');$m=new BaseCatalog;$img=$this->uploadImage('imagen','cables');$p=[$_POST['numero_cable'],$_POST['marca_id'],$_POST['calibre'],$_POST['tipo_enchufe'],$_POST['aislacion'],$_POST['largo'],$_POST['capacidad_aislacion'],$img,$_POST['estado'],$_POST['observacion']]; if(!empty($_POST['id'])){$p[]=$_POST['id'];$m->execSql('UPDATE cables SET numero_cable=?,marca_id=?,calibre=?,tipo_enchufe=?,aislacion=?,largo=?,capacidad_aislacion=?,imagen=COALESCE(?,imagen),estado=?,observacion=?,updated_at=NOW() WHERE id=?',$p);$id=(int)$_POST['id'];}else{$m->execSql('INSERT INTO cables(numero_cable,marca_id,calibre,tipo_enchufe,aislacion,largo,capacidad_aislacion,imagen,estado,observacion,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$p);$id=(int)\App\Core\App::db()->lastInsertId();}$m->audit('Guardar','Cables',$id,'Cable guardado');flash('success','Cable guardado.');redirect('cables');}
 public function historial($id):void{$this->requirePermission('Cables');$m=new BaseCatalog;$cable=$m->fetch('SELECT c.*, mc.nombre marca FROM cables c LEFT JOIN marcas_cable mc ON mc.id=c.marca_id WHERE c.id=?',[$id]);$informes=$m->fetchAll('SELECT * FROM informes_cable WHERE cable_id=? ORDER BY id DESC',[$id]);$this->view('cables/historial',compact('cable','informes'));}
}
